name = "tickets-platform"
type = "javascript"
account_id = "" # Fill in your Cloudflare account ID
workers_dev = true
route = ""
zone_id = "" # Fill in your Cloudflare zone ID if you have a custom domain
compatibility_date = "2023-12-01"

[site]
bucket = ".next/static"
entry-point = "."

[build]
command = "npm run build"
upload.format = "service-worker"

[build.upload]
format = "service-worker"

[observability.logs]
enabled = true
